name: Daily Book Scrape

on:
  schedule:
    - cron: '30 3 * * *'  # Runs at 9:00 AM IST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
